version: "2"

services:
  fastai:
    build:
        context: .
        dockerfile: Dockerfile
    image: huangyingw/fastai
    volumes:
        - ./.jupyter/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
        - ./.jupyter/jupyter_notebook_config.json:/root/.jupyter/jupyter_notebook_config.json
        - ./.jupyter/custom/custom.js:/root/.jupyter/custom/custom.js
        - ../fastai/fastai/:/root/fastai/
        - ./anaconda3/:/root/anaconda3/
        - ./.bashrc:/root/.bashrc
        - ./var/logs/:/var/logs/
    ports:  
        - "8888:8888"
    command: /bin/sh -c "/entrypoint.sh 2>&1 | tee /var/logs/containner.log"
