version: "2"

services:

  fastai:
    build:
        context: .
        dockerfile: Dockerfile
    image: huangyingw/fastai
    volumes:
      - ./.jupyter/jupyter_notebook_config.py:/root/.jupyter/jupyter_notebook_config.py
      - ./.jupyter/jupyter_notebook_config.json:/root/.jupyter/jupyter_notebook_config.json
      - ./.jupyter/custom/custom.js:/root/.jupyter/custom/custom.js
    ports:  
      - "8888:8888"
    command: /bin/sh -c "/entrypoint.sh"
