version: "2"

services:

  fastai:
    build:
        context: .
        dockerfile: Dockerfile
    image: huangyingw/fastai
    volumes:
      - ../fastai/courses/:/home/docker/fastai-courses/
      - ./vgg16.h5:/tmp/.keras/models/vgg16.h5
    ports:  
      - "8888:8888"
  
